# default values.yaml
# you can write your own by refering to the examples given under each section.
serviceName: test

namespace: test

labels: {}

autoscaling:
  min: 2
  max: 4
  metrics: {}
  behavior: {}

### example deployment ###

configmap: {}
deployment:
  affinity: {}
  image:
    repository: 741386957827.dkr.ecr.ap-south-1.amazonaws.com/dev-kb-payments-service
    tag: '20221207083306'
  podAnnotations: {}
  lifecycle:
    preStop:
      exec:
        command:
          - sh
          - '-c'
          - sleep 30
  args: {}
  resources: {}
  nodeSelector: {}
  tolerations: {}
  env: {}

health_check:
  path: "/health"
  port: 8080


ingress: {}

iam_role: {}

##############

### do not include this
test: "{{"