apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python_app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
{{- toYaml .Values.configmap.data | nindent 2 }}