{{- $serviceName := include "python_app.fullname" . -}}
{{- $namesoace := .Values.namespace -}}
{{- $lables := .Values.labels -}}
{{- $ingress := .Values.ingress -}}
{{- range $ingress }}
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ $namesoace }}
  {{- with .annotations }}  
  annotations:
    konghq.com/protocols: https
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- toYaml $lables | nindent 4 }}
spec:
  rules:
  {{- with .rules }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}