apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "python_app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}