apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python_app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- with .Values.iam_role }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}