apiVersion: v1
kind: Service
metadata:
  name: {{ include "python_app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  {{- if .Values.health_check.port }}
    - name: {{ include "python_app.fullname" . }}
      port: 80
      targetPort: {{ .Values.health_check.port }}
  {{- else }}
    - name: {{ include "python_app.fullname" . }}
      port: 80
      targetPort: 8080
  {{- end }}
  selector:
    {{- toYaml .Values.labels | nindent 4 }}